data : 'data_cfg/data/'
model_path : 'classification/models/'
interim_model_name : 'interim_model.pt'
final_model_name : 'resnet34_half.pt'
train_val_split : 0.7
epochs: 2 #40
batch_size: 4 #16
learning_rate: 0.001
momentum: 0.9

#Classifier layer config params
classifer_num_hidden_layers: 1
classifier_layer_size: 512
classifier_layer_dropout_prob: 0.05

#Pruning configs
# PRUNE_ROUNDS: 1
# MODEL_PATH: 'classification/models/resnet18.pt'
# PRUNE_CONV2D_LAYERS: True
# PRUNE_CONV2D_LAYER_PERCENTAGE: 0.1
# PRUNE_DENSE_LAYERS: True
# PRUNE_DENSE_LAYER_PERCENTAGE: 0.2
# PRUNE_STRATEGY: 'L1Strategy'
# INPUT_SHAPE: [1,3,224,224]